version: "3.7"
services:
  mqtt:
    build: vernemq/
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "off"
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: "off"
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: "on"
      DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: "off"
      DOCKER_VERNEMQ_USER_ROOT: "root"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_POSTGRES__ENABLED: "on"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__DATABASE: "vernemq"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__HOST: "database"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD_HASH_METHOD: "crypt"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PASSWORD: "root"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__PORT: "5432"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__POSTGRES__USER: "root"
    ports:
      - 1883:1883
    depends_on:
      - database

  database:
    build: postgres/
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "vernemq"
    ports:
      - 5433:5432
    volumes:
      - postgresData:/var/lib/postgresql/data

volumes:
  postgresData:
